spring.application.name=Enotes_API_Service
spring.datasource.url = jdbc:mysql://localhost:3306/enote_db
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.username = root
spring.datasource.password = root
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
# spring.datasource.ddl-auto = none
spring.jpa.hibernate.ddl-auto=none

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
file.upload.path = notes/

# Email send config
spring.mail.host=smtp.gmail.com
spring.mail.username=divyadityasingh111@gmail.com
spring.mail.password=dwdw lcnw cjyt yevi
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true